### ISSUE TITLE
Title of Blog posts are overlapping

### ISSUE THREAD

**Issue by ShaileshKumar007** [MLH-Fellowship/pod-4.1.2-portfolio#50]
**Describe the bug**
The title of blog posts are overlapping with the header of the page

**To Reproduce**
1. Go to 'https://prep-pod-4-1-2.netlify.app/'
2. Scroll down to 'Latest Posts'
3. Click on 'Post'

**Expected behavior**
Title of posts should not overlap with the header of the page.

**Screenshots**
![mlh pod](https://user-images.githubusercontent.com/71178959/136704274-1c3ead12-ea6e-408b-bdaa-b7e16df4ada9.JPG)

**Desktop (please complete the following information):**
 - OS: [All]
 - Browser [All]
 - Version [All]

**Smartphone (please complete the following information):**
 - Device: [All]
 - OS: [All]
 - Browser [All]
 - Version [All]

**Additional context**
NA

**Comment by Shubham0324** [comment]
@ShaileshKumar007 Thank you.
#49 commit added to solve this.

# Preview
https://deploy-preview-49--prep-pod-4-1-2.netlify.app/2018/08/20/lorem-ipsum-copy-3.html

**Comment by yashika51** [comment]
Thanks for reporting @ShaileshKumar007, 
Great job @Shubham0324!

**Comment by yashika51** [comment]
Closed via #49
